### ISSUE TITLE
Integration mode prototype

### ISSUE THREAD

**Issue by akiicat** [akiicat/nodori#3]
點擊 chrome extension 可以在現在的網頁上編輯自己的筆記

- 將所有的 element 加上 contenteditable
- 把打上的筆記儲存起來

**Comment by toumasaya** [comment]
![fullsizerender 1](https://cloud.githubusercontent.com/assets/12068201/26257218/59a8f464-3cf2-11e7-82e1-be0ab94d83e1.jpg)
